<a href="https://colab.research.google.com/github/lufergonza/copy/blob/main/TelecomX_parte_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Extracción del Archivo Tratado**

In [255]:
import pandas as pd

In [256]:
df = pd.read_csv("/content/datos_tratados.csv")

In [257]:
df

,customerid,churn,customer,phone,internet,account,gender,account_contract,account_metodo,tenure,total
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '...",Female,One year,Mailed check,9,593.30
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli...",Male,Month-to-month,Mailed check,9,542.40
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli...",Male,Month-to-month,Electronic check,4,280.85
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli...",Male,Month-to-month,Electronic check,13,1237.85
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli...",Female,Month-to-month,Mailed check,3,267.40
...,...,...,...,...,...,...,...,...,...,...,...
7038,9987-LUTYD,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '...",Female,One year,Mailed check,13,742.90
7039,9992-RRAMN,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli...",Male,Month-to-month,Electronic check,22,1873.70
7040,9992-UJOEL,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli...",Male,Month-to-month,Mailed check,2,92.75
7041,9993-LHIEB,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Two year', 'PaperlessBilling': '...",Male,Two year,Mailed check,67,4627.65
7042,9995-HOTOH,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'No', 'MultipleLines': 'No ph...","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Two year', 'PaperlessBilling': '...",Male,Two year,Electronic check,63,3707.60

In [258]:
df = df.drop(columns=["customer", "phone", "internet", "account"])

In [259]:
df

,customerid,churn,gender,account_contract,account_metodo,tenure,total
0,0002-ORFBO,No,Female,One year,Mailed check,9,593.30
1,0003-MKNFE,No,Male,Month-to-month,Mailed check,9,542.40
2,0004-TLHLJ,Yes,Male,Month-to-month,Electronic check,4,280.85
3,0011-IGKFF,Yes,Male,Month-to-month,Electronic check,13,1237.85
4,0013-EXCHZ,Yes,Female,Month-to-month,Mailed check,3,267.40
...,...,...,...,...,...,...,...
7038,9987-LUTYD,No,Female,One year,Mailed check,13,742.90
7039,9992-RRAMN,Yes,Male,Month-to-month,Electronic check,22,1873.70
7040,9992-UJOEL,No,Male,Month-to-month,Mailed check,2,92.75
7041,9993-LHIEB,No,Male,Two year,Mailed check,67,4627.65
7042,9995-HOTOH,No,Male,Two year,Electronic check,63,3707.60

##**Eliminación de Columnas Irrelevantes**

In [260]:
df = df.drop(columns=["customerid"])

In [261]:
df

     churn  gender account_contract    account_metodo  tenure    total
0       No  Female         One year      Mailed check       9   593.30
1       No    Male   Month-to-month      Mailed check       9   542.40
2      Yes    Male   Month-to-month  Electronic check       4   280.85
3      Yes    Male   Month-to-month  Electronic check      13  1237.85
4      Yes  Female   Month-to-month      Mailed check       3   267.40
...    ...     ...              ...               ...     ...      ...
7038    No  Female         One year      Mailed check      13   742.90
7039   Yes    Male   Month-to-month  Electronic check      22  1873.70
7040    No    Male   Month-to-month      Mailed check       2    92.75
7041    No    Male         Two year      Mailed check      67  4627.65
7042    No    Male         Two year  Electronic check      63  3707.60

[7043 rows x 6 columns]

In [262]:
df["churn"].value_counts()

churn
No     5174
Yes    1869
Name: count, dtype: int64

In [263]:
df["gender"].unique()

array(['Female', 'Male'], dtype=object)

In [264]:
df["gender"] = df["gender"].map({
   'Female' : 0,
    'Male': 1
})

In [265]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   churn             7043 non-null   object
 1   gender            7043 non-null   int64
 2   account_contract  7043 non-null   object
 3   account_metodo    7043 non-null   object
 4   tenure            7043 non-null   int64
 5   total             7032 non-null   float64
dtypes: float64(1), int64(2), object(3)
memory usage: 330.3+ KB

In [266]:
df.head(20)

   churn  gender account_contract             account_metodo  tenure    total
0     No       0         One year               Mailed check       9   593.30
1     No       1   Month-to-month               Mailed check       9   542.40
2    Yes       1   Month-to-month           Electronic check       4   280.85
3    Yes       1   Month-to-month           Electronic check      13  1237.85
4    Yes       0   Month-to-month               Mailed check       3   267.40
5     No       0   Month-to-month    Credit card (automatic)       9   571.45
6     No       0         Two year  Bank transfer (automatic)      71  7904.25
7     No       1         Two year    Credit card (automatic)      63  5377.80
8     No       0   Month-to-month           Electronic check       7   340.35
9     No       0         Two year               Mailed check      65  5957.90
10    No       1         Two year    Credit card (automatic)      54  2460.55
11    No       0         Two year    Credit card (automatic)      72  8456.75
12    No       0   Month-to-month           Electronic check       5   351.50
13    No       0         Two year  Bank transfer (automatic)      72  7261.25
14    No       0         Two year  Bank transfer (automatic)      56  2560.10
15    No       0         Two year    Credit card (automatic)      71  6849.40
16    No       0         One year               Mailed check      34  1993.20
17    No       0   Month-to-month           Electronic check       1    72.10
18   Yes       1         One year    Credit card (automatic)      45  2791.50
19   Yes       1   Month-to-month           Electronic check       1    25.10

In [267]:
df

     churn  gender account_contract    account_metodo  tenure    total
0       No       0         One year      Mailed check       9   593.30
1       No       1   Month-to-month      Mailed check       9   542.40
2      Yes       1   Month-to-month  Electronic check       4   280.85
3      Yes       1   Month-to-month  Electronic check      13  1237.85
4      Yes       0   Month-to-month      Mailed check       3   267.40
...    ...     ...              ...               ...     ...      ...
7038    No       0         One year      Mailed check      13   742.90
7039   Yes       1   Month-to-month  Electronic check      22  1873.70
7040    No       1   Month-to-month      Mailed check       2    92.75
7041    No       1         Two year      Mailed check      67  4627.65
7042    No       1         Two year  Electronic check      63  3707.60

[7043 rows x 6 columns]

####**Encoding**

In [268]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder

In [269]:
columnas = df.columns

In [270]:
one_hot = make_column_transformer((
    OneHotEncoder(drop = 'if_binary'),
    ['account_contract', 'account_metodo']
),
    remainder = 'passthrough',
    sparse_threshold=0,
    force_int_remainder_cols=False)

In [271]:
X = one_hot.fit_transform(df)

In [272]:
one_hot.get_feature_names_out(columnas)

array(['onehotencoder__account_contract_Month-to-month',
       'onehotencoder__account_contract_One year',
       'onehotencoder__account_contract_Two year',
       'onehotencoder__account_metodo_Bank transfer (automatic)',
       'onehotencoder__account_metodo_Credit card (automatic)',
       'onehotencoder__account_metodo_Electronic check',
       'onehotencoder__account_metodo_Mailed check', 'remainder__churn',
       'remainder__gender', 'remainder__tenure', 'remainder__total'],
      dtype=object)

In [273]:
 df =pd.DataFrame(X, columns = one_hot.get_feature_names_out(columnas))

In [274]:
df

,onehotencoder__account_contract_Month-to-month,onehotencoder__account_contract_One year,onehotencoder__account_contract_Two year,onehotencoder__account_metodo_Bank transfer (automatic),onehotencoder__account_metodo_Credit card (automatic),onehotencoder__account_metodo_Electronic check,onehotencoder__account_metodo_Mailed check,remainder__churn,remainder__gender,remainder__tenure,remainder__total
0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,No,0,9,593.3
1,1.0,0.0,0.0,0.0,0.0,0.0,1.0,No,1,9,542.4
2,1.0,0.0,0.0,0.0,0.0,1.0,0.0,Yes,1,4,280.85
3,1.0,0.0,0.0,0.0,0.0,1.0,0.0,Yes,1,13,1237.85
4,1.0,0.0,0.0,0.0,0.0,0.0,1.0,Yes,0,3,267.4
...,...,...,...,...,...,...,...,...,...,...,...
7038,0.0,1.0,0.0,0.0,0.0,0.0,1.0,No,0,13,742.9
7039,1.0,0.0,0.0,0.0,0.0,1.0,0.0,Yes,1,22,1873.7
7040,1.0,0.0,0.0,0.0,0.0,0.0,1.0,No,1,2,92.75
7041,0.0,0.0,1.0,0.0,0.0,0.0,1.0,No,1,67,4627.65
7042,0.0,0.0,1.0,0.0,0.0,1.0,0.0,No,1,63,3707.6

####**Verificación de la Proporción de Cancelación (Churn)**

In [275]:
df["remainder__churn"].value_counts()

remainder__churn
No     5174
Yes    1869
Name: count, dtype: int64

In [276]:
df.dtypes

onehotencoder__account_contract_Month-to-month             object
onehotencoder__account_contract_One year                   object
onehotencoder__account_contract_Two year                   object
onehotencoder__account_metodo_Bank transfer (automatic)    object
onehotencoder__account_metodo_Credit card (automatic)      object
onehotencoder__account_metodo_Electronic check             object
onehotencoder__account_metodo_Mailed check                 object
remainder__churn                                           object
remainder__gender                                          object
remainder__tenure                                          object
remainder__total                                           object
dtype: object

In [277]:
correlacion = df.corr()
correlacion

ValueError: could not convert string to float: 'No'

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,6))
sns.heatmap(correlacion, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Matriz de correlación")
plt.show()

####**Análisis de Correlación**

In [ ]:
correlacion = df[['remainder__churn', 'onehotencoder__account_contract_Two year']].corr()
print(correlacion)

In [ ]:
correlacion = df[['remainder__churn',"onehotencoder__account_metodo_Credit card (automatic)" ]].corr()
print(correlacion)

In [ ]:
correlacion = df[['remainder__churn', 'remainder__gender']].corr()
print(correlacion)

In [ ]:
correlacion = df[['remainder__churn', 'onehotencoder__account_contract_Month-to-month']].corr()
print(correlacion)

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
sns.boxplot(x="remainder__churn", y="remainder__tenure", data=df)
plt.title("Distribución de tiempo de contrato según la Cancelación")
plt.xlabel("Churn (0=No, 1=Sí)")
plt.ylabel("Tenure (meses)")
plt.show()

In [ ]:
plt.figure(figsize=(8,6))
sns.scatterplot(
   x="remainder__churn", y="remainder__tenure",
    hue="remainder__churn",
    palette="coolwarm",
    data=df
)
plt.title("Tenure vs Total gasto (coloreado por Churn)")
plt.xlabel("Tenure (meses)")
plt.ylabel("Total gasto")
plt.show()

In [ ]:
plt.figure(figsize=(8,6))
sns.boxplot(x="remainder__churn", y="remainder__tenure", data=df)
plt.show()

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
sns.boxplot(
    x="remainder__churn", y="remainder__tenure",
    hue="remainder__churn",
    palette="coolwarm",
    data=df

)
plt.title("Tenure vs Churn")
plt.xlabel("Churn (0 = No, 1 = Yes)")
plt.ylabel("Tenure (meses)")
plt.show()

####**Separación de Datos**

In [ ]:
df

In [ ]:
columnas_vacias = df.columns[df.isna().all()]
print(columnas_vacias)

In [ ]:
(df.isna().mean() * 100).sort_values(ascending=False)

In [ ]:
x= df.drop('remainder__churn', axis = 1)

y = df['remainder__churn']

In [ ]:
x

In [ ]:
y = df['remainder__churn']
y

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify = y,  random_state = 5)

####**Creación de Modelos**

In [ ]:
from sklearn.dummy import DummyClassifier

In [ ]:
dummy = DummyClassifier()
dummy.fit(X_train, y_train)

dummy.score(X_test, y_test)

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
modelo_arbol = DecisionTreeClassifier(random_state =5)
modelo_arbol.fit(X_train, y_train)

In [ ]:
modelo_arbol.predict(X_test)

In [ ]:
modelo_arbol.score(X_test, y_test)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
normalizacion = MinMaxScaler()
X_train_normalizado = normalizacion.fit_transform(X_train)

In [ ]:
pd.DataFrame(X_train_normalizado)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn = KNeighborsClassifier()

In [ ]:
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

modelo_knn = make_pipeline(
    SimpleImputer(strategy="mean"),   # 🔥 rellena NaN
    StandardScaler(),                 # 🔥 normaliza
    KNeighborsClassifier(n_neighbors=5)
)

modelo_knn.fit(X_train, y_train)
y_pred_knn = modelo_knn.predict(X_test)

In [ ]:
modelo_knn.fit(X_train, y_train)

In [ ]:
X_test_normalizado = normalizacion.transform(X_test)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
modelo_rf = RandomForestClassifier(random_state=42)
modelo_rf.fit(X_train, y_train)

y_pred_rf = modelo_rf.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

def evaluar_modelo(nombre, y_test, y_pred):
    print(f"\nModelo: {nombre}")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred))
    print("Recall:", recall_score(y_test, y_pred))
    print("F1-score:", f1_score(y_test, y_pred))
    print("Matriz de Confusión:\n", confusion_matrix(y_test, y_pred))

In [ ]:

evaluar_modelo("Random Forest", y_test, y_pred_rf)